apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbornet-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harbornet
  template:
    metadata:
      labels:
        app: harbornet
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: harbornet-app
          image: harbornet-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
